server:
  port: 7233
  host: "0.0.0.0"

targets:
  - source: "<namespace>.<account>.internal"
    target: "<namespace>.<account>.tmprl.cloud:7233"
    tls:
      cert_file: "/path/to/<namespace>.<account>/tls.crt"
      key_file: "/path/to/<namespace>.<account>/tls.key"
    encryption_key: "<key>"
    namespace: "<namespace>.<account>"

  - source: "<namespace>.<account>.internal"
    target: "<namespace>.<account>.tmprl.cloud:7233"
    tls:
      cert_file: "/path/to/<namespace>.<account>/tls.crt"
      key_file: "/path/to/<namespace>.<account>/tls.key"
    encryption_key: "<key>"
    namespace: "<namespace>.<account>"
